name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit and Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Linter
        run: flake8 src/

      - name: Run Unit Tests
        run: pytest src/tests/test_unit.py

      - name: Run Integration Tests
        run: pytest src/tests/test_integration.py

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd-pipeline-guidelines:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/cicd-pipeline-guidelines:latest ${{ secrets.DOCKER_USERNAME }}/cicd-pipeline-guidelines:${{ github.sha }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/cicd-pipeline-guidelines:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cicd-pipeline-guidelines:${{ github.sha }}
